// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fartltsfwubdoohzoumw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcnRsdHNmd3ViZG9vaHpvdW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjIyNTMsImV4cCI6MjA3MzU5ODI1M30.FcgE2uq3TRAH4xsyvLOT82h0YOBHHYd3A6wnxLIEUsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});